object ISFAddDomainLIPLink: TISFAddDomainLIPLink
  Left = 0
  Top = 0
  Width = 720
  Height = 462
  RenderInvisibleControls = False
  OnRender = IWAppFormRender
  AllowPageAccess = True
  ConnectionMode = cmAny
  Title = 'StratDB'
  OnCreate = IWAppFormCreate
  Background.Fixed = False
  HandleTabs = False
  LeftToRight = True
  LockUntilLoaded = False
  LockOnSubmit = True
  ShowHint = True
  DesignLeft = 2
  DesignTop = 2
  object IWDBEdit1: TIWDBEdit
    AlignWithMargins = False
    Left = 242
    Top = 108
    Width = 73
    Height = 21
    StyleRenderOptions.RenderBorder = False
    Editable = False
    NonEditableAsLabel = True
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.Style = [fsBold]
    Font.PxSize = 12
    FriendlyName = 'IWDBEdit1'
    SubmitOnAsyncEvent = True
    TabOrder = 2
    AutoEditable = False
    DataField = 'UNITID'
    DataSource = dmStrat.dsDomainLIP
    PasswordPrompt = False
  end
  object iwbReturn: TIWButton
    AlignWithMargins = False
    Left = 102
    Top = 72
    Width = 104
    Height = 25
    Caption = 'Return'
    Color = clWebLIGHTGREEN
    Font.Size = 9
    Font.PxSize = 12
    FriendlyName = 'iwbReturn'
    OnClick = iwbReturnClick
  end
  object IWLabel1: TIWLabel
    AlignWithMargins = False
    Left = 104
    Top = 110
    Width = 64
    Height = 15
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.PxSize = 12
    HasTabOrder = False
    FriendlyName = 'IWLabel1'
    Caption = 'Domain ID'
  end
  object IWLabel2: TIWLabel
    AlignWithMargins = False
    Left = 104
    Top = 136
    Width = 143
    Height = 15
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.PxSize = 12
    HasTabOrder = False
    FriendlyName = 'IWLabel2'
    Caption = 'Large Igneous Province'
  end
  object iwbCancelUpdates: TIWButton
    AlignWithMargins = False
    Left = 440
    Top = 72
    Width = 104
    Height = 25
    Caption = 'Cancel Updates'
    Color = clWebLIGHTSALMON
    Font.Size = 9
    Font.PxSize = 12
    FriendlyName = 'iwbCancelUpdates'
    TabOrder = 6
    OnClick = iwbCancelUpdatesClick
  end
  object rectLeft: TIWRectangle
    AlignWithMargins = False
    Left = 0
    Top = 55
    Width = 83
    Height = 407
    Align = alLeft
    ZIndex = 1
    Font.PxSize = 13
    Font.Color = clWebBLACK
    BorderOptions.Width = 0
    FriendlyName = 'rectLeft'
    Color = clWebLAVENDER
    Alignment = taLeftJustify
    VAlign = vaMiddle
    ExplicitHeight = 350
  end
  object iwDBlcbLink: TIWDBLookupComboBox
    AlignWithMargins = False
    Left = 240
    Top = 132
    Width = 365
    Height = 21
    StyleRenderOptions.RenderBorder = False
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.Style = [fsBold]
    Font.PxSize = 12
    Editable = False
    NonEditableAsLabel = True
    TabOrder = 3
    AutoEditable = True
    DataField = 'DOMAINID'
    DataSource = dmStrat.dsDomainLIP
    FriendlyName = 'iwDBlcbLink'
    KeyField = 'DOMAINID'
    ListField = 'DOMAINNAME'
    ListSource = dmStrat.dsDomains
    DisableWhenEmpty = True
  end
  object iwDBnLink: TIWDBNavigator
    AlignWithMargins = False
    Left = 104
    Top = 206
    Width = 150
    Height = 28
    Confirmations.Delete = 'Are you sure you want to delete this record?'
    Confirmations.Post = 'Are you sure you want to update this record?'
    Confirmations.Cancel = 'Are you sure you want to cancel your changes to this record?'
    DataSource = dmStrat.dsDomainLIP
    FriendlyName = 'iwDBnLink'
    ImageHeight = 24
    ImageWidth = 24
    VisibleButtons = [nbFirst, nbPrior, nbNext, nbLast, nbInsert]
    Orientation = orHorizontal
    OnInsert = iwDBnLinkInsert
  end
  object iwDBgLink: TIWDBGrid
    AlignWithMargins = False
    Left = 104
    Top = 240
    Width = 601
    Height = 185
    BorderColors.Color = clNone
    BorderColors.Light = clNone
    BorderColors.Dark = clNone
    BGColor = clNone
    BorderSize = 1
    BorderStyle = tfDefault
    CellPadding = 0
    CellSpacing = 0
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.PxSize = 12
    FrameBuffer = 40
    Lines = tlAll
    UseFrame = True
    UseSize = True
    ShowEmptyCells = True
    ShowInvisibleRows = True
    ScrollToCurrentRow = False
    Columns = <
      item
        Alignment = taLeftJustify
        BGColor = clNone
        DoSubmitValidation = True
        Font.FontName = 'Arial'
        Font.Size = 8
        Font.PxSize = 10
        Header = False
        Height = '0'
        ShowHint = True
        VAlign = vaMiddle
        Visible = True
        Width = '0'
        Wrap = False
        RawText = False
        BlobCharLimit = 0
        CompareHighlight = hcNone
        DataField = 'UNITID'
        Title.Alignment = taCenter
        Title.BGColor = clNone
        Title.DoSubmitValidation = True
        Title.Font.FontName = 'Arial'
        Title.Font.Size = 8
        Title.Font.Style = [fsBold]
        Title.Font.PxSize = 10
        Title.Header = False
        Title.Height = '0'
        Title.ShowHint = True
        Title.Text = 'Unit ID'
        Title.VAlign = vaMiddle
        Title.Visible = True
        Title.Width = '0'
        Title.Wrap = False
        Title.RawText = True
      end
      item
        Alignment = taCenter
        BGColor = clNone
        DoSubmitValidation = True
        Font.FontName = 'Arial'
        Font.Size = 8
        Font.PxSize = 10
        Header = False
        Height = '0'
        ShowHint = True
        VAlign = vaMiddle
        Visible = True
        Width = '0'
        Wrap = False
        RawText = False
        BlobCharLimit = 0
        CompareHighlight = hcNone
        DataField = 'DOMAINID'
        Title.Alignment = taCenter
        Title.BGColor = clNone
        Title.DoSubmitValidation = True
        Title.Font.FontName = 'Arial'
        Title.Font.Size = 8
        Title.Font.Style = [fsBold]
        Title.Font.PxSize = 10
        Title.Header = False
        Title.Height = '0'
        Title.ShowHint = True
        Title.Text = 'Domain ID'
        Title.VAlign = vaMiddle
        Title.Visible = True
        Title.Width = '0'
        Title.Wrap = False
        Title.RawText = True
      end
      item
        Alignment = taCenter
        BGColor = clNone
        DoSubmitValidation = True
        Font.FontName = 'Arial'
        Font.Size = 8
        Font.PxSize = 10
        Header = False
        Height = '0'
        ShowHint = True
        VAlign = vaMiddle
        Visible = True
        Width = '0'
        Wrap = False
        RawText = False
        BlobCharLimit = 0
        CompareHighlight = hcNone
        DataField = 'DOMAINNAME'
        Title.Alignment = taCenter
        Title.BGColor = clNone
        Title.DoSubmitValidation = True
        Title.Font.FontName = 'Arial'
        Title.Font.Size = 8
        Title.Font.Style = [fsBold]
        Title.Font.PxSize = 10
        Title.Header = False
        Title.Height = '0'
        Title.ShowHint = True
        Title.Text = 'Domain'
        Title.VAlign = vaMiddle
        Title.Visible = True
        Title.Width = '0'
        Title.Wrap = False
        Title.RawText = True
      end
      item
        Alignment = taCenter
        BGColor = clNone
        DoSubmitValidation = True
        Font.FontName = 'Arial'
        Font.Size = 8
        Font.PxSize = 10
        Header = False
        Height = '0'
        ShowHint = True
        VAlign = vaMiddle
        Visible = True
        Width = '0'
        Wrap = False
        RawText = False
        BlobCharLimit = 0
        CompareHighlight = hcNone
        DataField = 'INC4CHTYN'
        Title.Alignment = taCenter
        Title.BGColor = clNone
        Title.DoSubmitValidation = True
        Title.Font.FontName = 'Arial'
        Title.Font.Size = 8
        Title.Font.Style = [fsBold]
        Title.Font.PxSize = 10
        Title.Header = False
        Title.Height = '0'
        Title.ShowHint = True
        Title.Text = 'Inc.'
        Title.VAlign = vaMiddle
        Title.Visible = True
        Title.Width = '0'
        Title.Wrap = False
        Title.RawText = True
      end>
    DataSource = dmStrat.dsDomainLIP
    FooterRowCount = 0
    FriendlyName = 'iwDBgLink'
    FromStart = True
    HighlightColor = clNone
    HighlightRows = False
    Options = [dgShowTitles]
    RefreshMode = rmAutomatic
    RowLimit = 0
    RollOver = True
    RowClick = False
    RollOverColor = clWebLIGHTGOLDENRODYELLOW
    RowHeaderColor = clWebCADETBLUE
    RowAlternateColor = clNone
    RowCurrentColor = clWebYELLOW
  end
  object iwbDeleteLink: TIWButton
    AlignWithMargins = False
    Left = 560
    Top = 72
    Width = 145
    Height = 25
    Caption = 'Delete Current Record'
    Color = clWebLIGHTCORAL
    Font.Size = 9
    Font.PxSize = 12
    FriendlyName = 'iwbDeleteLink'
    TabOrder = 7
    OnClick = iwbDeleteLinkClick
  end
  object iwbEdit: TIWButton
    AlignWithMargins = False
    Left = 216
    Top = 72
    Width = 104
    Height = 25
    Caption = 'Edit'
    Color = clWebLEMONCHIFFON
    Font.Size = 9
    Font.PxSize = 12
    FriendlyName = 'iwbEdit'
    TabOrder = 1
    OnClick = iwbEditClick
  end
  object iwbApplyUpdates: TIWButton
    AlignWithMargins = False
    Left = 326
    Top = 72
    Width = 104
    Height = 25
    Caption = 'Apply Updates'
    Color = clWebPEACHPUFF
    Font.Size = 9
    Font.PxSize = 12
    FriendlyName = 'iwbApplyUpdates'
    TabOrder = 5
    OnClick = iwbApplyUpdatesClick
  end
  object IWLabel3: TIWLabel
    AlignWithMargins = False
    Left = 104
    Top = 160
    Width = 79
    Height = 15
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.PxSize = 12
    HasTabOrder = False
    FriendlyName = 'IWLabel1'
    Caption = 'Incl. for Chart'
  end
  object iwDBlcbInc4Cht: TIWDBLookupComboBox
    AlignWithMargins = False
    Left = 240
    Top = 159
    Width = 129
    Height = 21
    StyleRenderOptions.RenderBorder = False
    Font.FontName = 'Arial'
    Font.Size = 9
    Font.Style = [fsBold]
    Font.PxSize = 12
    Editable = False
    NonEditableAsLabel = True
    TabOrder = 4
    AutoEditable = True
    DataField = 'INC4CHTYN'
    DataSource = dmStrat.dsDomainLIP
    FriendlyName = 'iwDBlcbInc4Cht'
    KeyField = 'YESNOID'
    ListField = 'YESNO'
    ListSource = dmStrat.dsYesNo
    DisableWhenEmpty = True
  end
  inline TopBar: TISFTopBarStrat
    Left = 0
    Top = 0
    Width = 720
    Height = 55
    HorzScrollBar.Visible = False
    VertScrollBar.Visible = False
    Align = alTop
    Constraints.MaxHeight = 55
    Constraints.MinHeight = 55
    Constraints.MinWidth = 600
    Color = clNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 0
    TabStop = True
    ExplicitWidth = 720
    inherited IWFrameRegion: TIWRegion
      Width = 720
      TabOrder = 8
      ExplicitWidth = 720
      inherited iwrHeader: TIWRegion
        Width = 720
        ExplicitWidth = 720
        inherited iwrWelcome: TIWRegion
          Width = 720
          ExplicitWidth = 720
          inherited iwrDisplayUserName: TIWRegion
            Width = 520
            ExplicitWidth = 520
            inherited lblWelcome: TIWLabel
              Left = 247
              Font.Color = clWebDARKSLATEGRAY
              ExplicitLeft = 247
            end
          end
        end
        inherited iwrSignInOut: TIWRegion
          Width = 720
          ExplicitWidth = 720
          inherited iwlSignOut: TIWLink
            Font.Color = clWebBLUE
          end
          inherited lnkSignIn: TIWLink
            Font.Color = clWebBLUE
          end
          inherited lblProgTitle: TIWLabel
            Font.Color = clWebSTEELBLUE
          end
        end
      end
    end
  end
end
