object ISFLIPGrid: TISFLIPGrid
  Left = 0
  Top = 0
  Width = 1349
  Height = 1000
  Margins.Left = 4
  Margins.Top = 4
  Margins.Right = 4
  Margins.Bottom = 4
  RenderInvisibleControls = False
  OnRender = IWAppFormRender
  AllowPageAccess = True
  ConnectionMode = cmAny
  OnCreate = IWAppFormCreate
  Background.Fixed = False
  HandleTabs = False
  LeftToRight = True
  LockUntilLoaded = False
  LockOnSubmit = False
  ShowHint = True
  PixelsPerInch = 120
  DesignLeft = 2
  DesignTop = 2
  object rectRight: TIWRectangle
    AlignWithMargins = False
    Left = 1344
    Top = 69
    Width = 5
    Height = 931
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alRight
    Font.PxSize = 13
    Font.Color = clWebBLACK
    BorderOptions.Width = 0
    FriendlyName = 'rectRight'
    Color = clWebLIGHTSLATEGRAY
    Alignment = taLeftJustify
    VAlign = vaMiddle
  end
  object IWRectangle1: TIWRectangle
    AlignWithMargins = False
    Left = 1339
    Top = 69
    Width = 5
    Height = 931
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alRight
    Font.PxSize = 13
    Font.Color = clWebBLACK
    BorderOptions.Width = 0
    FriendlyName = 'rectRight'
    Color = clWebLIGHTSLATEGRAY
    Alignment = taLeftJustify
    VAlign = vaMiddle
  end
  object IWRegion1: TIWRegion
    Left = 0
    Top = 69
    Width = 250
    Height = 931
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    RenderInvisibleControls = False
    Align = alLeft
    BorderOptions.NumericWidth = 0
    BorderOptions.Style = cbsNone
    inline FrameMenu: TISFFrameMenu
      Left = 0
      Top = 0
      Width = 250
      Height = 931
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      HorzScrollBar.Visible = False
      VertScrollBar.Visible = False
      Align = alLeft
      AutoScroll = True
      TabOrder = 0
      TabStop = True
      ExplicitWidth = 250
      ExplicitHeight = 931
      inherited IWFrameRegion: TIWRegion
        Width = 250
        Height = 931
        TabOrder = 4
        ExplicitWidth = 250
        ExplicitHeight = 931
        inherited IWRegion1: TIWRegion
          Width = 250
          Height = 931
          ExplicitWidth = 250
          ExplicitHeight = 931
          inherited IWMenu1: TIWMenu
            Height = 831
            MainMenuStyle.MenuItemFont.Color = clWebINDIGO
            MainMenuStyle.SelectedMenuItemFont.Color = clWebINDIGO
            MainMenuStyle.DisabledMenuItemFont.Color = clWebSILVER
            SubMenuStyle.MenuItemFont.Color = clWebINDIGO
            SubMenuStyle.SelectedMenuItemFont.Color = clWebINDIGO
            SubMenuStyle.DisabledMenuItemFont.Color = clWebSILVER
            ExplicitHeight = 831
          end
          inherited IWRegion2: TIWRegion
            Width = 250
            ExplicitWidth = 250
            inherited IWRegion3: TIWRegion
              Width = 250
              ExplicitWidth = 250
              inherited IWImageStratDB: TIWImage
                Width = 200
                Height = 97
                ExplicitWidth = 200
                ExplicitHeight = 97
              end
              inherited IWImageIGCP509: TIWImage
                Width = 250
                ExplicitWidth = 250
              end
            end
          end
        end
      end
    end
  end
  object IWRegion2: TIWRegion
    Left = 250
    Top = 69
    Width = 1089
    Height = 931
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    RenderInvisibleControls = False
    Align = alClient
    BorderOptions.NumericWidth = 0
    BorderOptions.Style = cbsNone
    object iwDBgResults: TIWDBGrid
      AlignWithMargins = False
      Left = 0
      Top = 71
      Width = 1089
      Height = 860
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alClient
      BorderColors.Color = clNone
      BorderColors.Light = clNone
      BorderColors.Dark = clNone
      BGColor = clNone
      BorderSize = 1
      BorderStyle = tfDefault
      CellPadding = 2
      CellSpacing = 0
      Font.FontName = 'Arial'
      Font.Size = 8
      Font.PxSize = 10
      FrameBuffer = 40
      Lines = tlAll
      UseFrame = False
      UseSize = True
      ShowEmptyCells = True
      ShowInvisibleRows = True
      ScrollToCurrentRow = False
      Columns = <
        item
          Alignment = taRightJustify
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = False
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'LIPID'
          LinkField = 'LIPID'
          OnClick = IWDBGrid1Columns0Click
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'ID'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = False
          Title.RawText = True
        end
        item
          Alignment = taLeftJustify
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = True
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'LIPNAME'
          LinkField = 'LIPID'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Event'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = False
          Title.RawText = True
        end
        item
          Alignment = taLeftJustify
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = True
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'LIPSIZEDESCRIPTION'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Size'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = True
          Title.RawText = True
        end
        item
          Alignment = taCenter
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = True
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'MINPLOTAGE'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Min. Age'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = True
          Title.RawText = True
        end
        item
          Alignment = taCenter
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = True
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'MAXPLOTAGE'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Max. Age'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = False
          Title.RawText = True
        end
        item
          Alignment = taCenter
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = False
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'BARCODEAGE'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Barcode'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = False
          Title.RawText = True
        end
        item
          Alignment = taRightJustify
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = True
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'SPOTLATITUDE'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Spot Lat.'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = True
          Title.RawText = True
        end
        item
          Alignment = taRightJustify
          BGColor = clNone
          DoSubmitValidation = True
          Font.FontName = 'Arial'
          Font.Size = 8
          Font.PxSize = 10
          Header = False
          Height = '0'
          ShowHint = True
          VAlign = vaMiddle
          Visible = True
          Width = '0'
          Wrap = True
          RawText = False
          BlobCharLimit = 0
          CompareHighlight = hcNone
          DataField = 'SPOTLONGITUDE'
          OnTitleClick = IWDBGrid1ColumnsTitleClick
          Title.Alignment = taCenter
          Title.BGColor = clNone
          Title.DoSubmitValidation = True
          Title.Font.FontName = 'Arial'
          Title.Font.Size = 8
          Title.Font.Style = [fsBold]
          Title.Font.PxSize = 10
          Title.Header = False
          Title.Height = '0'
          Title.ShowHint = True
          Title.Text = 'Spot Lon.'
          Title.VAlign = vaMiddle
          Title.Visible = True
          Title.Width = '0'
          Title.Wrap = True
          Title.RawText = True
        end>
      DataSource = dmLIP.dsLIPQuery
      FooterRowCount = 0
      FriendlyName = 'iwDBgResults'
      FromStart = False
      HighlightColor = clNone
      HighlightRows = False
      Options = [dgShowTitles]
      RefreshMode = rmAutomatic
      RowLimit = 25
      RollOver = True
      RowClick = False
      RollOverColor = clWebPALEGOLDENROD
      RowHeaderColor = clWebLIGHTSTEELBLUE
      RowAlternateColor = clNone
      RowCurrentColor = clNone
    end
    object IWRegion3: TIWRegion
      Left = 0
      Top = 0
      Width = 1089
      Height = 71
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      HorzScrollBar.Visible = False
      VertScrollBar.Visible = False
      RenderInvisibleControls = False
      Align = alTop
      BorderOptions.NumericWidth = 0
      BorderOptions.Style = cbsNone
      DesignSize = (
        1089
        71)
      object iwbDownload: TIWButton
        AlignWithMargins = False
        Left = 903
        Top = 8
        Width = 161
        Height = 31
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Anchors = [akTop, akRight]
        Caption = 'Download to Excel'
        Color = clBtnFace
        Font.Size = 9
        Font.PxSize = 12
        FriendlyName = 'iwbDownload'
        OnClick = iwbDownloadClick
      end
      object iwlFirstPage: TIWLink
        AlignWithMargins = False
        Left = 38
        Top = 43
        Width = 41
        Height = 21
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        RenderSize = False
        StyleRenderOptions.RenderSize = False
        Alignment = taLeftJustify
        Color = clNone
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.Style = [fsUnderline]
        Font.PxSize = 12
        Font.Color = clWebBLUE
        HasTabOrder = True
        DoSubmitValidation = False
        FriendlyName = 'iwlFirstPage'
        OnClick = iwlFirstPageClick
        TabOrder = 1
        RawText = False
        Caption = 'First'
      end
      object iwlLastPage: TIWLink
        AlignWithMargins = False
        Left = 300
        Top = 43
        Width = 44
        Height = 21
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        RenderSize = False
        StyleRenderOptions.RenderSize = False
        Alignment = taLeftJustify
        Color = clNone
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.Style = [fsUnderline]
        Font.PxSize = 12
        Font.Color = clWebBLUE
        HasTabOrder = True
        DoSubmitValidation = False
        FriendlyName = 'iwlLastPage'
        OnClick = iwlLastPageClick
        TabOrder = 2
        RawText = False
        Caption = 'Last'
      end
      object iwlNextPage: TIWLink
        AlignWithMargins = False
        Left = 258
        Top = 43
        Width = 43
        Height = 21
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        RenderSize = False
        StyleRenderOptions.RenderSize = False
        Alignment = taLeftJustify
        Color = clNone
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.Style = [fsUnderline]
        Font.PxSize = 12
        Font.Color = clWebBLUE
        HasTabOrder = True
        DoSubmitValidation = False
        FriendlyName = 'iwlNextPage'
        OnClick = iwlNextPageClick
        TabOrder = 3
        RawText = False
        Caption = 'Next'
      end
      object iwlPrevPage: TIWLink
        AlignWithMargins = False
        Left = 88
        Top = 43
        Width = 66
        Height = 21
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        RenderSize = False
        StyleRenderOptions.RenderSize = False
        Alignment = taLeftJustify
        Color = clNone
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.Style = [fsUnderline]
        Font.PxSize = 12
        Font.Color = clWebBLUE
        HasTabOrder = True
        DoSubmitValidation = False
        FriendlyName = 'iwlPrevPage'
        OnClick = iwlPrevPageClick
        TabOrder = 5
        RawText = False
        Caption = 'Previous'
      end
      object iwlPageNumTotal: TIWLabel
        AlignWithMargins = False
        Left = 216
        Top = 44
        Width = 15
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.PxSize = 12
        HasTabOrder = False
        FriendlyName = 'iwlPageNumTotal'
        Caption = '11'
      end
      object iwlSortedBy: TIWLabel
        AlignWithMargins = False
        Left = 875
        Top = 46
        Width = 188
        Height = 18
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Anchors = [akTop, akRight]
        Font.FontName = 'Arial'
        Font.Size = 8
        Font.Style = [fsItalic]
        Font.PxSize = 10
        NoWrap = True
        HasTabOrder = False
        FriendlyName = 'iwlSortedBy'
        Caption = 'Sorted as specified in query'
      end
      object iwlPageNum: TIWLabel
        AlignWithMargins = False
        Left = 170
        Top = 44
        Width = 14
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taRightJustify
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.PxSize = 12
        HasTabOrder = False
        FriendlyName = 'IWLabel1'
        Caption = '11'
      end
      object lblRecordCount: TIWLabel
        AlignWithMargins = False
        Left = 38
        Top = 16
        Width = 145
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.PxSize = 12
        NoWrap = True
        HasTabOrder = False
        FriendlyName = 'lblRecordCount'
        Caption = 'records match the query'
      end
      object iwlOf: TIWLabel
        AlignWithMargins = False
        Left = 195
        Top = 44
        Width = 11
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Font.FontName = 'Arial'
        Font.Size = 9
        Font.PxSize = 12
        HasTabOrder = False
        FriendlyName = 'iwlOf'
        Caption = 'of'
      end
      object iwbCalcBarcodeAges: TIWButton
        AlignWithMargins = False
        Left = 560
        Top = 25
        Width = 176
        Height = 31
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Caption = 'Calc. Barcode Ages'
        Color = clBtnFace
        FriendlyName = 'iwbCalcBarcodeAges'
        TabOrder = 6
        OnClick = iwbCalcBarcodeAgesClick
      end
    end
  end
  inline TopBar: TISFTopBarStrat
    Left = 0
    Top = 0
    Width = 1349
    Height = 69
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    HorzScrollBar.Visible = False
    VertScrollBar.Visible = False
    Align = alTop
    Constraints.MaxHeight = 69
    Constraints.MinHeight = 69
    Constraints.MinWidth = 750
    Color = clNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 2
    TabStop = True
    ExplicitWidth = 1349
    inherited IWFrameRegion: TIWRegion
      Width = 1349
      TabOrder = 7
      ExplicitWidth = 1349
      inherited iwrHeader: TIWRegion
        Width = 1349
        ExplicitWidth = 1349
        inherited iwrWelcome: TIWRegion
          Width = 1349
          ExplicitWidth = 1349
          inherited iwrDisplayUserName: TIWRegion
            Width = 1099
            ExplicitWidth = 1099
            inherited lblWelcome: TIWLabel
              Left = 978
              Font.Color = clWebDARKSLATEGRAY
              ExplicitLeft = 758
            end
          end
        end
        inherited iwrSignInOut: TIWRegion
          Width = 1349
          ExplicitWidth = 1349
          inherited iwlSignOut: TIWLink
            Font.Color = clWebBLUE
          end
          inherited lnkSignIn: TIWLink
            Font.Color = clWebBLUE
          end
          inherited lblProgTitle: TIWLabel
            Font.Color = clWebSTEELBLUE
          end
        end
      end
    end
  end
end
